# .github/workflows/update-news.yml (correct version)
name: Update Yemeni News
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggers

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install feedparser beautifulsoup4 requests
      
      - name: Scrape news
        run: python scripts/scrape_news.py
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/news.json
          git commit -m "Auto-update news [skip ci]"
          git push
